### ISSUE TITLE
Installing plugin leads to error when calling its initGui() method

### ISSUE THREAD

**Issue by leonmvd** [rduivenvoorde/pdokservicesplugin#12]
Bij het installeren van de plugin op MacOS (10.12.6) krijg ik de volgende error.

```
Couldn't load plugin 'pdokservicesplugin' due to an error when calling its initGui() method 

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 5978441: ordinal not in range(128) 
Traceback (most recent call last):
  File "/usr/local/Cellar/qgis3-dev/2.99/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 345, in startPlugin
    plugins[packageName].initGui()
  File "/Users/leon/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pdokservicesplugin/pdokservicesplugin.py", line 170, in initGui
    self.run(True)
  File "/Users/leon/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pdokservicesplugin/pdokservicesplugin.py", line 419, in run
    self.pdok = json.load(f)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 5978441: ordinal not in range(128)


Python version: 3.6.3 (default, Oct  4 2017, 06:09:15) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)] 
QGIS version: 2.99.0-Master Master, ded892e 

Python Path:
/usr/local/Cellar/qgis3-dev/2.99/QGIS.app/Contents/MacOS/../Resources/python/plugins/processing
/usr/local/Cellar/qgis3-dev/2.99/QGIS.app/Contents/MacOS/../Resources/python
/Users/leon/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/leon/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/usr/local/Cellar/qgis3-dev/2.99/QGIS.app/Contents/MacOS/../Resources/python/plugins
/usr/local/opt/gdal2-python/lib/python3.6/site-packages
/usr/local/opt/qgis3-dev/lib/python3.6/site-packages
/usr/local/opt/qgis3-dev/libexec/python/lib/python/site-packages
/usr/local/lib/python3.6/site-packages
/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python36.zip
/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6
/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload
/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
/usr/local/Cellar/numpy/1.13.3/libexec/nose/lib/python3.6/site-packages
/Users/leon/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/leon/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary
/Users/leon/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary/extlibs
```

**Comment by rduivenvoorde** [comment]
@leonmvd kun je misschien zelf proberen te achterhalen welk character in die pdok.json het probleem is?
Onder Linux en Windows is blijkbaar datzelfde char niet een probleem :-(

Ik heb zelf geen mac, dus kan dit niet testen, maar als jij door wat trial en error weet te achterhalen welke string het probleem is, probeer ik eromheen te werken.

**Comment by leonmvd** [comment]
Het zat hem in "met een bouwjaar van voor 1970 in **regio's** met een minder draagkrachtige bodem"
Als ik de apostrof weghaal laadt de plugin zonder problemen.

**Comment by leonmvd** [comment]
Wat vreemd is, want regio's komt veel vaker voor in de json

**Comment by rduivenvoorde** [comment]
Hoi Leon, mmm ik zal er even naar kijken. Ik denk dat het komt doordat er dan 'vreemde' tekens uit andere encoding in de json zitten. Ik heb dat eerder gezien, in sommige descriptions van services zitten vreemde tekens (waarschijnlijk Windows-Charset tekens die worden gestuurd als utf-8 oid).. Ik doe daarvoor een 'zoek en vervang' bij het creeren van de json.

Dank je wel voor het uitzoeken!

**Comment by rduivenvoorde** [comment]
Vreemd trouwens dat in Python 3.6
json.load(f)
uiteindelijk 
codecs.ascii_decode(input, self.errors)[0]
dus als ascii probeert te decoden?

**Comment by evetion** [comment]
Zelfde probleem op Mac, dit is op te lossen door in `pdokservicesplugin.py` op r421 de encoding toe te voegen: 
`f = open(pdokjson, 'r', encoding='utf-8')`

Dit werkt geloof ik alleen voor Python 3.
