### ISSUE TITLE
Upgrade PDOK-plugin mislukt

### ISSUE THREAD

**Issue by emacgillavry** [rduivenvoorde/pdokservicesplugin#76]
Couldn't load plugin 'pdokservicesplugin' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'owslib.coverage.wcs201' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/username/.local/share/QGIS/QGIS3/profiles/default/python/plugins/pdokservicesplugin/__init__.py", line 28, in classFactory
    from .pdokservicesplugin import PdokServicesPlugin
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/username/.local/share/QGIS/QGIS3/profiles/default/python/plugins/pdokservicesplugin/pdokservicesplugin.py", line 69, in 
    from .processing_provider.provider import Provider
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/username/.local/share/QGIS/QGIS3/profiles/default/python/plugins/pdokservicesplugin/processing_provider/provider.py", line 8, in 
    from .processing_ahn3 import PDOKWCSTool
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/username/.local/share/QGIS/QGIS3/profiles/default/python/plugins/pdokservicesplugin/processing_provider/processing_ahn3.py", line 13, in 
    from owslib.coverage.wcs201 import WebCoverageService_2_0_1
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'owslib.coverage.wcs201'

Python version: 3.6.9 (default, Mar 15 2022, 13:55:28) [GCC 8.4.0] 
QGIS version: 3.16.3-Hannover Hannover, 94ac9f21b8 

Python Path:
/usr/share/qgis/python
/home/username/.local/share/QGIS/QGIS3/profiles/default/python
/home/username/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python36.zip
/usr/lib/python3.6
/usr/lib/python3.6/lib-dynload
/usr/local/lib/python3.6/dist-packages
/usr/lib/python3/dist-packages
/home/username/.local/share/QGIS/QGIS3/profiles/default/python
/home/username/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web
/home/username/.local/share/QGIS/QGIS3/profiles/default/python/plugins

**Comment by rduivenvoorde** [comment]
@emacgillavry was dit al bij het upgraden van de plugin naar 4.0.0? python 3.6... best oud

@arbakker voor de processing_ahn3 is de owslib nodig? Waar komt die normaal vandaan?

**Comment by emacgillavry** [comment]
Yup, was bij het upgraden naar 4.0.0... 😳

**Comment by rduivenvoorde** [comment]
@emacgillavry ik heb de opstart van het algorithme in de plugin aangepast, zodat tenminste de plugin (en QGIS) gewoon laadt wanneer er iets mis is (ikzelf had een foutmelding wanneer er geen netwerk was)...

Dus ik hoop dat je tenminste de rest van de plugin kunt gebruiken.

Wil je dat evt even testen wanneer ik (hopelijk later op de dag) 4.1.0 release?

Om dat ahn3 algorithme te gebruiken, zul je denk ik de python owslib moeten installeren...

**Comment by arbakker** [comment]
Ik was in de veronderstelling dat OWSLib meegeinstalleerd wordt met QGIS, dit [issue](https://github.com/qgis/QGIS/issues/47360) lijkt daar iig op te wijzen. Maar helemaal zeker ben ik daar niet van...

**Comment by rduivenvoorde** [comment]
@emacgillavry kun je 4.2.0 eens proberen? 

Ik neem een beetje aan dat dit gefixed is intussen, heropen ajb anders dit issue.
